package:
  name: "pdfminer"
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0').replace('v', '') + '.' + environ.get('GIT_DESCRIBE_NUMBER', '0') }}

source:
  git_url: git@github.com:building-estimates/pdfminer.six.git
  git_tag: master

requirements:
  build:
    - python 3.8
    - setuptools
    - numpy 1.21
    - chardet
    - cryptography
    - sortedcontainers

  run:
    - python 3.8
    - numpy 1.21
    - chardet
    - cryptography
    - sortedcontainers
    - shapely

test:
  imports:
    - pdfminer

about:
  home: https://https://github.com/building-estimates/pdfminer.six
