package:
  name: "pdfminer"
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0').replace('v', '') + '.' + environ.get('GIT_DESCRIBE_NUMBER', '0') }}

source:
  git_url: git@github.com:building-estimates/pdfminer.six.git
  git_tag: master
requirements:
  build:
    # Changed to target the latest stable Python versions (e.g., 3.12)
    - python 
    - setuptools    
    - numpy
    - chardet
    - cryptography
    - sortedcontainers

  run:
    # Changed to target the latest stable Python versions (e.g., 3.12)
    - python     
    - numpy
    - chardet
    - cryptography
    - sortedcontainers
    - shapely

test:
  imports:
    - pdfminer

about:
  home: https://https://github.com/building-estimates/pdfminer.six
